### ISSUE TITLE
Support for week

### ISSUE THREAD

**Issue by brendan-pike** [JurajMlich/ultimate-bash-backup-script-with-rotation#5]
Love the script, very effective.  I've tried using this flag, 8x1w hoping that it would capture a weekly dump but it doesn't appear to work.  
Is something like this possible?

**Comment by JurajMlich** [comment]
Hi @brendan-pike , check the updated script, 8x1w should now work properly!

**Comment by brendan-pike** [comment]
A 3 minute feature update, that has to be a serious record, certainly is in my lifetime! Cheers

**Comment by JurajMlich** [comment]
Haha, enjoy!
